---
title: "stats_outputs"
author: "Emma"
date: "11/14/2021"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(ggpubr)
library(PairedData)
library(rstatix)

asp <- read.csv("/Volumes/SeaGate Wilkinson/Capstone2021/captsone_2021_frogs/data_raw/ASP_data.csv", header = TRUE)
gtm <- read.csv("/Volumes/SeaGate Wilkinson/Capstone2021/captsone_2021_frogs/data_raw/GTM_data.csv", header = TRUE)
```


#### One Way Repeated Measures ANOVA

```{r, echo = FALSE}

#summarize and visualize data
summarydf <- asp %>%
    gather(key = "treatment", value = "call_rate", RateBefore, RateDuring, RateAfter) %>%
    convert_as_factor(treatment) #prepare a df with a column called "treatment" that shows before/during/after

#add an ID column to df bc the ANOVA test needs it
summarydf$ID <- seq(1: 282) #282 is the dim of summarydf

summarydf <- summarydf %>% convert_as_factor(ID) #convert ID into a factor type

summarydf %>%
    group_by(treatment) %>%
    get_summary_stats(call_rate, type = "mean_sd") #get mean call rate and sd of treatments

```


```{r, echo = FALSE}

bxp <- ggboxplot(summarydf,
                 x = "treatment",
                 y = "call_rate",
                 xlab = "Treatment",
                 ylab = "Call rate",
                 main = "Call Rates Before, During, and After Noise Events at ASP",
                 order = c("RateBefore", "RateDuring", "RateAfter"),
                 font.label = list(size = 26, color = "black"),
                 ggtheme = theme_gray()) # create boxplot of treatments
bxp

```

### check ANOVA assumptions

```{r, echo = FALSE}

#identify extreme outliers
# extremeo <- summarydf %>%
#     group_by(treatment) %>%
#     identify_outliers(call_rate) #no extreme outliers

#assess normality
# ggqqplot(summarydf, "call_rate", facet.by = "treatment")
#it's not perfect but let's run the test anyways

```
### Run ANOVA

```{r}

# anova <- anova_test(data = summarydf, dv = call_rate, wid = ID, within = treatment)
# get_anova_table(aov.test)

```

```{r}
anova.1 <- aov(call_rate ~ treatment, data = summarydf)

summary(anova.1)
```
#### Two Sample T-Test

```{r, echo = FALSE}

#We predict that the mean population call rate of species at asp will be different than the mean population call rate of species at the gtm
#H0:m asp = m gtm
#Ha:m asp != m gtm

#summarize and visualize data
ttestdf <- read.csv("/Volumes/SeaGate Wilkinson/Capstone2021/captsone_2021_frogs/data_raw/2_samp_ttest_df.csv", header = TRUE)

#summary stats
group_by(ttestdf, Site) %>%
    summarise(
        count = n(),
        mean = mean(CallRate, na.rm = TRUE),
        sd = sd(CallRate, na.rm = TRUE)
    )


```


```{r, echo = FALSE}

#plot
bxp <- ggboxplot(ttestdf, x = "Site", y = "CallRate", 
          color = "Site", palette = c("#000000", "#000000"),
          ylab = "Call Rate", xlab = "Site",
          main = "ASP has Larger Distribution of Call Rate",
          font.label = list(size = 26, color = "black"),
          ggtheme = theme_gray())
bxp <- ggpar(bxp, legend = "none")
bxp

```

### check t-test assumptions

```{r, echo = FALSE}

### check assumptions
# are the populations independent?
    # yes. different locations
# do the data follow normal distribution?
ggqqplot(ttestdf, "CallRate", facet.by = "Site")
    #it's fine...
#do the populations have the same variance?
ftest <- var.test(CallRate ~ Site, data = ttestdf)
ftest
# the variances are significantly different. We need to use Welch ttest

```


```{r}

### compute t test
ttest <- t.test(CallRate ~ Site, data = ttestdf, alternative = c("two.sided"), var.equal = FALSE) #var.equal = FALSE b/c population variances != -- this runs a Welch ttest to make up for it
ttest
#pval = 0.72

```

